version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"

  [analyzers.exclude]
  - "explicit-import-specific-method"
  - "jsx-props-no-functions"
  - "JS-C1003"