version = 1

test_patterns = [
  "src/**/__tests__/**",
  "src/**/*.test.ts",
  "src/**/*.test.tsx",
  "src/**/testing/**",
  "src/__mocks__/**",
  "src/setupTests.tsx",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"
