version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"

  [[analyzers.ignore]]
  message = "Explicitly import the specific method needed"