name: slim/deploy-to-firebase

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  deploy-firebase:
    name: "Deploy to Firebase"
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.34.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: REACT_APP_CONFIG=preview PUBLIC_URL=/ pnpm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SLIM }}"
          projectId: idc-external-006
          channelId: live
