name: Build and push Docker image

on:
  push:
    branches: [midas-dev] # push latest on midas-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build, tag, and push image to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_REPOSITORY: midas-slim-viewer
          COMMIT_SHA: ${{ github.sha }}
        run: |
          IMAGE_TAG=${COMMIT_SHA::7}
          docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:contributor-dev-$IMAGE_TAG -f docker-midas-dev .
          docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPOSITORY:contributor-dev-$IMAGE_TAG
